services:
  - type: web
    name: EnvX
    env: python
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.app:app"   
    domains:
      - envx.onrender.com 